version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/sbstjn/go-lambda-example

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: |
          apt-get -y -qq update
          apt-get -y -qq install python3.4-dev
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3.4 get-pip.py --user
          pip install awscli --upgrade --user
      - run: touch .env
      - run: make install

      - run: make test      
      - run: make build

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - run: make package
      - run: make deploy

      - store_artifacts:
          path: /go/src/github.com/sbstjn/go-lambda-example/dist
          destination: binaries
      - store_artifacts:
          path: /go/src/github.com/sbstjn/go-lambda-example/package.yml