version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/sbstjn/go-lambda-example

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: touch .env
      - run: make install
      - run: go get github.com/jstemmer/go-junit-report

      - run:
          name: Run unit tests
          command: make test
      
      - run: make build

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_artifacts:
          path: /go/src/github.com/sbstjn/go-lambda-example/dist
          destination: dist