defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/golang:1.8

whitelist: &whitelist
  paths:
    - "*.*"
version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: go get -v -t -d ./...

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run tests
          command: make test


workflows:
  version: 2

  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout