version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
  working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  steps:
    - checkout
    # specify any bash command here prefixed with `run: `
    - run: go get -v -t -d ./...
    - run: make test